### ISSUE TITLE
Cache miniconda installations on travis?

### ISSUE THREAD

**Issue by ceball** [pyviz/pyct#1]
I.e. for each build, $HOME/miniconda would be extracted from the cache, then conda install dependencies would run (which will only update things that have changed), then the cache would be updated.

In many ways, this could be a better test than installing from scratch, since most users will be updating existing conda installations/environments rather than starting from scratch.

Installing miniconda and dependencies from scratch every time takes up a lot of the total build time for many projects (particularly the smaller projects).

**Comment by jbednar** [comment]
I'm all for it, and have been wondering whether that was possible several times over the past few days while watching builds spend most of their time fetching miniconda.  If it's practical, please please do it!

**Comment by ceball** [comment]
Caching does indeed seem to speed things up (usually cache store/fetch and update dependencies seems to take about 1-1.5 minutes, while creating a conda installation from scratch can take much longer).

However, caching will inevitably come with some complications. Some of those will be ones faced by users anyway, while some will come from managing the cache(s) in general...

**Comment by jbednar** [comment]
That sounds as expected; why close this?

**Comment by ceball** [comment]
Sorry, I forgot to say that it's implemented (e.g. in datashader WIP packaging PR),
which is why I closed it. It will be part of the documentation here (probably as example Travis config, or link to example), along with some other ci system specific things.

**Comment by jbednar** [comment]
Ah, now that makes sense, thanks!
