### ISSUE TITLE
Ensure pyviz websites are up

### ISSUE THREAD

**Issue by ceball** [pyviz/pyct#4]
Jim: "make sure that all our websites are basically still up and running, a few times a day"

Maybe something like https://www.pingdom.com/free or https://uptimerobot.com/

**Comment by ceball** [comment]
Will start with uptimerobot. That just checks the website's up, and provides some history. 

Emails Jim and me for now, but might be good to have some kind of shared status alert email address @pyviz.org.

I set a check interval of 60 mins (the default is 5...not sure we need that for pyviz ;) ).

We could have a daily travis job that checks the websites are serving expected content (e.g. check for something on homepage), but that is probably overkill.

AWS might have something, but I don't have access to the sites on AWS.

**Comment by jbednar** [comment]
Thanks!
